=== foundeo/cfdocs/data/cfdocs.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "engineDetail": {
      "title": "Engine Detail",
      "type": "object",
      "properties": {
        "minimum_version": {
          "title": "Minimum version",
          "description": "The version of the engine in which this was introduced",
          "type": "string",
          "pattern": "^((0|[1-9]\\d*)(\\.(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))?)?)?$"
        },
        "deprecated": {
          "title": "Deprecated version",
          "description": "The version of the engine in which this was deprecated",
          "type": "string",
          "pattern": "^((0|[1-9]\\d*)(\\.(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))?)?)?$",
          "default": ""
        },
        "removed": {
          "title": "Removed version",
          "description": "The version of the engine in which this was removed",
          "type": "string",
          "pattern": "^((0|[1-9]\\d*)(\\.(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))?)?)?$",
          "default": ""
        },
        "notes": {
          "title": "Notes",
          "description": "Additional notes about engine compatibility",
          "type": "string",
          "default": ""
        },
        "docs": {
          "title": "Docs",
          "description": "Link to engine-specific documentation",
          "type": "string",
          "default": ""
        }
      },
      "required": [
        "minimum_version"
      ]
    },
    "engines": {
      "title": "Engines",
      "type": "object",
      "properties": {
        "coldfusion": {
          "title": "ColdFusion",
          "description": "Engine details for ColdFusion",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        },
        "railo": {
          "title": "Railo",
          "description": "Engine details for Railo",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        },
        "lucee": {
          "title": "Lucee",
          "description": "Engine details for Lucee",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        },
        "openbd": {
          "title": "OpenBD",
          "description": "Engine details for OpenBD",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        }
      }
    },
    "params": {
      "title": "Parameters",
      "description": "List of parameters",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Parameter",
        "description": "Argument or attribute",
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "description": "Parameter name",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "description": "Description of the parameter",
            "type": "string"
          },
          "type": {
            "title": "Type",
            "description": "The data type of the parameter",
            "type": "string",
            "enum": [
              "any",
              "array",
              "binary",
              "boolean",
              "component",
              "date",
              "function",
              "guid",
              "numeric",
              "query",
              "string",
              "struct",
              "uuid",
              "variableName",
              "xml"
            ]
          },
          "required": {
            "title": "Required",
            "description": "Whether this parameter is required",
            "type": "boolean"
          },
          "default": {
            "title": "Default",
            "description": "The default value of the parameter when not provided",
            "type": "string",
            "default": ""
          },
          "values": {
            "title": "Values",
            "description": "List of enumerated values for the parameter",
            "type": "array",
            "minItems": 0,
            "items": {
              "title": "Value",
              "description": "One of the enumerated values for the parameter",
              "type": "string"
            },
            "default": []
          },
          "engines": {
            "title": "Engines",
            "description": "Engine compatibility information",
            "type": "object",
            "$ref": "#/definitions/engines"
          },
          "callback_params": {
            "title": "Callback Parameters",
            "description": "When type is function, this represents the parameters for the callback",
            "type": "array",
            "$ref": "#/definitions/params",
            "minItems": 0,
            "default": []
          }
        },
        "required": [
          "name",
          "description",
          "type",
          "required"
        ]
      },
      "default": []
    }
  },
  "title": "CFDocs",
  "description": "CFDocs data file",
  "type": "object",
  "properties": {
    "name": {
      "title": "Name",
      "description": "The name of the tag or function. Start with lowercase.",
      "type": "string",
      "pattern": "^[a-z]\\w+$"
    },
    "description": {
      "title": "Description",
      "description": "A short description of the item",
      "type": "string"
    },
    "type": {
      "title": "Type",
      "description": "Whether this refers to a function, tag, or listing",
      "type": "string",
      "enum": [
        "function",
        "tag",
        "listing"
      ]
    },
    "syntax": {
      "title": "Syntax",
      "description": "The basic syntax of the tag or function",
      "type": "string",
      "default": ""
    },
    "script": {
      "title": "Syntax",
      "description": "For tags, shows how the tag would be invoked from cfscript.",
      "type": "string",
      "default": ""
    },
    "member": {
      "title": "Member",
      "description": "Deprecated. For functions, shows the available member function syntax.",
      "type": "string",
      "default": ""
    },
    "member_details": {
      "title": "Member Details",
      "description": "For details of the member function equivalent of this function.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "The name of the member function. Start with lowercase.",
          "type": "string",
          "pattern": "^[a-z]\\w+$"
        },
        "type": {
          "title": "Type",
          "description": "The data type for which this function is a member",
          "type": "string",
          "enum": [
            "array",
            "boolean",
            "date",
            "image",
            "locale",
            "query",
            "string",
            "struct",
            "spreadsheet",
            "xml"
          ]
        },
        "returns": {
          "title": "Return Type",
          "description": "The return type of the member function.",
          "type": "string",
          "enum": [
            "any",
            "array",
            "binary",
            "boolean",
            "date",
            "function",
            "guid",
            "numeric",
            "query",
            "string",
            "struct",
            "uuid",
            "variableName",
            "void",
            "xml"
          ],
          "default": "void"
        },
        "engines": {
          "title": "Engines",
          "description": "Engine compatibility information",
          "type": "object",
          "$ref": "#/definitions/engines"
        },
        "base_param_index": {
          "title": "Base Param Index",
          "description": "A 1-based index referencing the param on which the member function is based",
          "type": "number",
          "default": 1
        }
      },
      "required": [
        "name",
        "type",
        "returns"
      ]
    },
    "returns": {
      "title": "Return Type",
      "description": "The return type of a function",
      "type": "string",
      "enum": [
        "any",
        "array",
        "binary",
        "boolean",
        "date",
        "function",
        "guid",
        "numeric",
        "query",
        "string",
        "struct",
        "uuid",
        "variableName",
        "void",
        "xml"
      ],
      "default": "void"
    },
    "related": {
      "title": "Related",
      "description": "A list of tag or function names that are related to this item",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Entity name",
        "description": "The name of a function or tag that is already documented",
        "type": "string"
      },
      "default": []
    },
    "discouraged": {
      "title": "Discouraged",
      "description": "If this key exists and has content a warning is displayed stating that the tag or function is discouraged by the CFML community.",
      "type": "string",
      "default": ""
    },
    "params": {
      "title": "Parameters",
      "description": "List of parameters",
      "type": "array",
      "$ref": "#/definitions/params",
      "minItems": 0,
      "default": []
    },
    "engines": {
      "title": "Engines",
      "description": "Engine compatibility information",
      "type": "object",
      "$ref": "#/definitions/engines"
    },
    "links": {
      "title": "Links",
      "description": "A list of external references",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Link",
        "description": "Information about the reference",
        "type": "object",
        "properties": {
          "title": {
            "title": "Title",
            "description": "A title for the link",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "description": "A description for the link",
            "type": "string"
          },
          "url": {
            "title": "URL",
            "description": "The link URL",
            "type": "string"
          }
        },
        "required": [
          "title",
          "description",
          "url"
        ]
      },
      "default": []
    },
    "examples": {
      "title": "Examples",
      "description": "A list of examples",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Example",
        "description": "Information about the example",
        "type": "object",
        "properties": {
          "title": {
            "title": "Title",
            "description": "Name of the code example",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "description": "Description of the code example",
            "type": "string"
          },
          "code": {
            "title": "Code",
            "description": "The example code",
            "type": "string"
          },
          "result": {
            "title": "Result",
            "description": "The expected output of the code example",
            "type": "string"
          },
          "runnable": {
            "title": "Runnable",
            "description": "Whether the code is runnable",
            "type": "boolean"
          }
        },
        "required": [
          "title",
          "description",
          "code"
        ]
      },
      "default": []
    }
  },
  "required": [
    "name",
    "description",
    "type"
  ]
}

=== foundeo/cfdocs/data/en/cfobjectcache.json
{
	"name":"cfobjectcache",
	"type":"tag",
	"syntax":"<cfobjectcache action=\"clear\">",
	"related":["cfobject"],
	"description":"Flushes the query cache.",
	"params": [
		{"name":"action","description":"clear: Clears queries from the cache in the Application\n scope","required":true,"default":"clear","type":"string","values":["clear"]}
	],
	"engines": {
		"coldfusion": {"minimum_version":"", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-m-o/cfobjectcache.html"},
		"lucee": {"minimum_version":"", "notes":"", "docs":"http://docs.lucee.org/reference/tags/objectcache.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/tag/cfobjectcache"},
		"openbd": {"minimum_version":"", "notes":"", "docs":"http://openbd.org/manual/?/tag/cfobjectcache"}
	},
	"links": []
}

=== foundeo/cfdocs/data/en/imagepaste.json
{
	"name":"imagePaste",
	"type":"function",
	"syntax":"imagePaste(image1, image2, x, y)",
	"member":"someImage.paste(image2, x, y)",
	"returns":"void",
	"related":[],
	"description":" Takes two images and an (x,y) coordinate and draws the second image over the first image with the upper-left corner at coordinate (x,y).",
	"params": [
		{"name":"image1","description":"The bottom image.","required":true,"default":"","type":"string","values":[]},
		{"name":"image2","description":"The image that is pasted on top of image1.","required":true,"default":"","type":"string","values":[]},
		{"name":"x","description":"The x coordinate where the upper-left corner of image2 is pasted.","required":true,"default":"","type":"numeric","values":[]},
		{"name":"y","description":"The y coordinate where the upper-left corner of image2 is pasted.","required":true,"default":"","type":"numeric","values":[]}

	],
	"engines": {
		"coldfusion": {"minimum_version":"8", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-h-im/imagepaste.html"},
		"lucee": {"minimum_version":"4.5", "notes":"", "docs":"https://docs.lucee.org/reference/functions/imagepaste.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/function/imagepaste"},
		"openbd": {"minimum_version":"", "notes":"", "docs":"http://openbd.org/manual/?/function/imagepaste"}
	},
	"links": [

	],
    "examples": [
		{
			"title": "Tag Syntax",
			"description": "This example shows how to copy a small rectangular area of one image and paste it over a larger image.",
			"code": "<!--- Create a ColdFusion image from an existing JPEG file and name it \"myImage1\". ---> \r\n <cfimage source=\"../cfdocs/images/artgallery/jeff05.jpg\" name=\"myImage1\"> \r\n <!--- Create a ColdFusion image from an existing JPEG file and name it \"myImage2\". ---> \r\n <cfimage source=\"../cfdocs/images/artgallery/maxwell01.jpg\" name=\"myImage2\"> \r\n <!--- Copy a rectangular region of myImage1. ---> \r\n <cfset resImage = imageCopy(myImage1,1,1,50,50)> \r\n <!--- Paste the rectangular area over myImage2. ---> \r\n <cfset imagePaste(myImage2,resImage,100,100)> \r\n <!--- Write the second ColdFusion image to result.jpg. ---> \r\n <cfimage source=\"#myImage2#\" action=\"write\" destination=\"test_myImage.jpg\" overwrite=\"yes\"> \r\n <!--- Display the two source images and the new image. ---> \r\n <img src=\"../cfdocs/images/artgallery/jeff05.jpg\"/> \r\n <img src=\"../cfdocs/images/artgallery/maxwell01.jpg\"/> \r\n <img src=\"test_myImage.jpg\"/> ",
			"result": "",
			"runnable":false
		},{
			"title":"Using paste member function",
			"description":"CF11+ Lucee4.5+ Copy the center of the image, rotate it 180 degrees about its center and paste it back into the original image",
			"code":"imgObj = imageRead(\"http://cfdocs.org/apple-touch-icon.png\");\r\ncopiedImgObj = imgObj.copy(50,50,50,50);\r\ncopiedImgObj.rotate(25,25,180,\"bicubic\");\r\nimgObj.paste(copiedImgObj,50,50);\r\ncfimage(action=\"writeToBrowser\", source=imgObj);",
			"result":"",
			"runnable":true
		}
	]

}

=== foundeo/cfdocs/data/en/sendgatewaymessage.json
{
	"name":"sendGatewayMessage",
	"type":"function",
	"syntax":"sendGatewayMessage(gatewayID, data)",
	"returns":"string",
	"related":[],
	"description":" Sends an outgoing message through a ColdFusion MX event gateway.",
	"params": [
		{"name":"gatewayID","description":"Identifier of the gateway to send the message.","required":true,"default":"","type":"string","values":[]},
		{"name":"data","description":"A ColdFusion structure.","required":true,"default":"","type":"struct","values":[]}

	],
	"engines": {
		"coldfusion": {"minimum_version":"", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-s/sendgatewaymessage.html"},
		"lucee": {"minimum_version":"", "notes":"", "docs":"https://docs.lucee.org/reference/functions/sendgatewaymessage.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/function/sendgatewaymessage"}
	},
	"links": [

	]

}

=== foundeo/cfdocs/data/en/cfexit.json
{
	"name":"cfexit",
	"type":"tag",
	"syntax":"<cfexit>",
	"script":"exit;",
	"related":["cfabort","cferror","cfthrow"],
	"description":"This tag aborts processing of the currently executing CFML\n custom tag, exits the page within the currently executing CFML\n custom tag, or re-executes a section of code within the\n currently executing CFML custom tag.",
	"params": [
		{"name":"method","description":"exittag: aborts processing of currently executing tag\n exittemplate: exits page of currently executing tag\n loop: reexecutes body of currently executing tag","required":false,"default":"","type":"string","values":["exittag","exittemplate","loop"]}
	],
	"engines": {
		"coldfusion": {"minimum_version":"3", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-d-e/cfexit.html"},
		"lucee": {"minimum_version":"", "notes":"", "docs":"https://docs.lucee.org/reference/tags/exit.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/tag/cfexit"},
		"openbd": {"minimum_version":"", "notes":"", "docs":"http://openbd.org/manual/?/tag/cfexit"}
	},
	"links": [],
	"examples": [
		{
			"title":"Simple cfexit example",
			"description":"Here the loop over the 5 number. When it's meet the condition as true then the block of code get exit.",
			"code":"<cfoutput>\r\n<cfloop from=\"1\" to=\"5\" index = \"i\">\r\n<cfif i EQ 3>\r\n\t<cfexit>\r\n<cfelse>\r\n\t#i#\r\n</cfif>\r\n</cfloop>\r\n</cfoutput>",
			"result":"1 2"
		}
		
	]
}

=== foundeo/cfdocs/data/en/onmissingtemplate.json
{
 	"name":"onMissingTemplate",
 	"type":"function",
 	"syntax":"function onMissingTemplate(string targetPage) { return true; }",
 	"returns":"boolean",
 	"related":["application-cfc"],
 	"description":"Defined in Application.cfc, invoked when a request is made for a CFML template that does not exist.",
 	"params": [
 		{"name":"targetPage","description":"Requested template path relative to the webroot","required":true,"default":"","type":"string","values":[]}
 	],
 	"engines": {
 		"coldfusion": {"minimum_version":"8", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/application-cfc-reference/onmissingtemplate.html"},
 		"lucee": {"minimum_version":"", "notes":"", "docs":""}
 	},
 	"links": [

 	]

 }

=== foundeo/cfdocs/data/en/arraymerge.json
{
	"name": "arrayMerge",
	"type": "function",
	"syntax": "arrayMerge(array1, array2 [, leaveIndex])",
	"member": "array1.merge(array2 [, leaveIndex])",
	"returns": "array",
	"related": ["arrayAppend"],
	"description": "This function creates a new array with data from the two passed arrays. To add all the data from one array into another without creating a new array see the built in function ArrayAppend(arr1, arr2, true).",
	"params": [
		{"name": "array1", "description": "", "required": true, "default": "", "type": "array", "values": []},
		{"name": "array2", "description": "", "required": true, "default": "", "type": "array", "values": []},
		{"name": "leaveIndex", "description": "", "required": false, "default": "", "type": "boolean", "values": []}
	],
	"engines": {
		"lucee": {"minimum_version": "", "notes": "", "docs": "http://docs.lucee.org/reference/functions/arraymerge.html"}
	},
  	"examples": [
		 {
			"title": "Standard function syntax",
			"description": "Lucee4.5+ Merge two arrays resulting in a single re-indexed array. All elements of both arrays are preserved.",
			"code": "fruit = ['apple','banana','orange'];\nveggies = ['tomato','carrot','corn','peas','peppers'];\nhealthyFoods = arrayMerge(fruit, veggies);\nwriteOutput(arrayToList(healthyFoods));",
			"result": "apple,banana,orange,tomato,carrot,corn,peas,peppers",
			"runnable":true
		 },
		 {
			"title": "Member function syntax",
			"description": "Lucee4.5+ Merge two arrays resulting in a single re-indexed array. All elements of both arrays are preserved.",
			"code": "fruit = ['apple','banana','orange'];\nveggies = ['tomato','carrot','corn','peas','peppers'];\nhealthyFoods = fruit.merge(veggies);\nwriteOutput(arrayToList(healthyFoods));",
			"result": "apple,banana,orange,tomato,carrot,corn,peas,peppers",
			"runnable":true
		 },
		 {
			"title": "Example where leaveIndex parameter is true",
			"description": "Lucee4.5+ Merge two arrays resulting in a single re-indexed array. Where the both arrays have elements in the same position, only values from the first array are included in the result. Valid using standard or member function syntax.\n\nNote how the first three elements of the veggies array are not merged because the fruit array already has values for elements 1-3.",
			"code": "fruit = ['apple','banana','orange'];\nveggies = ['tomato','carrot','corn','peas','peppers'];\nhealthyFoods = arrayMerge(fruit, veggies, true);\nwriteOutput(arrayToList(healthyFoods));",
			"result": "apple,banana,orange,peas,peppers",
			"runnable":true
		 }
	],
	"links": []
}

=== foundeo/cfdocs/data/en/inputbasen.json
{
	"name":"inputBaseN",
	"type":"function",
	"syntax":"inputBaseN(String, radix)",
	"returns":"numeric",
	"related":["int","parseNumber","toNumeric"],
	"description":"Converts string, using the base specified by radix, to an integer.",
	"params": [
		{"name":"String","description":"","required":true,"default":"","type":"string","values":[]},
		{"name":"radix","description":"","required":true,"default":"","type":"string","values":[]}
	],
	"engines": {
		"coldfusion": {"minimum_version":"", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-in-k/inputbasen.html"},
		"lucee": {"minimum_version":"", "notes":"", "docs":"https://docs.lucee.org/reference/functions/inputbasen.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/function/inputbasen"},
		"openbd": {"minimum_version":"", "notes":"", "docs":"http://openbd.org/manual/?/function/inputbasen"}
	},
	"links": [],
	"examples": [
		{
			"title":"Binary string to decimal",
			"description":"",
			"code":"inputBaseN(\"1010\",2)",
			"result":"10",
			"runnable":true
		},
		{
			"title":"Hexadecimal string to decimal",
			"description":"",
			"code":"inputBaseN(\"3FF\",16)",
			"result":"1023",
			"runnable":true
		},
		{
			"title":"Decimal string to decimal",
			"description":"",
			"code":"inputBaseN(\"125\",10)",
			"result":"125",
			"runnable":true
		},
		{
			"title":"Binary number to decimal",
			"description":"",
			"code":"inputBaseN(1010,2)",
			"result":"10",
			"runnable":true
		}
	]
}

=== foundeo/cfdocs/data/en/cachegetallids.json
{
	"name":"cacheGetAllIds",
	"type":"function",
	"syntax":"cacheGetAllIds()",
	"returns":"array",
	"related":["cacheGet","cacheGetAll"],
	"description":" Gets the IDs of all objects stored in the cache.",
	"params": [],
	"engines": {
		"coldfusion": {"minimum_version":"9", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-c-d/CacheGetAllIds.html"},
		"lucee": {"minimum_version":"", "notes":"", "docs":"https://docs.lucee.org/reference/functions/cachegetallids.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/function/cachegetallids"}
	},
	"links": [],
	"examples": [
		{
			"title":"cfscript",
			"description":"Gets the IDs of all objects stored in the cache.",
			"code":"<cfscript>    cacheRemoveAll();\r\n    cachePut(\"1\", \"1\");\r\n    cachePut(\"2\", \"2\");\r\n    writeOutput(serializeJson(CacheGetAllIds()));\r\n</cfscript>",
			"result":"[\"1\",\"2\"]",
			"runnable":true
		}
	]
}
