=== foundeo/cfdocs/data/cfdocs.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "engineDetail": {
      "title": "Engine Detail",
      "type": "object",
      "properties": {
        "minimum_version": {
          "title": "Minimum version",
          "description": "The version of the engine in which this was introduced",
          "type": "string",
          "pattern": "^((0|[1-9]\\d*)(\\.(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))?)?)?$"
        },
        "deprecated": {
          "title": "Deprecated version",
          "description": "The version of the engine in which this was deprecated",
          "type": "string",
          "pattern": "^((0|[1-9]\\d*)(\\.(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))?)?)?$",
          "default": ""
        },
        "removed": {
          "title": "Removed version",
          "description": "The version of the engine in which this was removed",
          "type": "string",
          "pattern": "^((0|[1-9]\\d*)(\\.(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))?)?)?$",
          "default": ""
        },
        "notes": {
          "title": "Notes",
          "description": "Additional notes about engine compatibility",
          "type": "string",
          "default": ""
        },
        "docs": {
          "title": "Docs",
          "description": "Link to engine-specific documentation",
          "type": "string",
          "default": ""
        }
      },
      "required": [
        "minimum_version"
      ]
    },
    "engines": {
      "title": "Engines",
      "type": "object",
      "properties": {
        "coldfusion": {
          "title": "ColdFusion",
          "description": "Engine details for ColdFusion",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        },
        "railo": {
          "title": "Railo",
          "description": "Engine details for Railo",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        },
        "lucee": {
          "title": "Lucee",
          "description": "Engine details for Lucee",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        },
        "openbd": {
          "title": "OpenBD",
          "description": "Engine details for OpenBD",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        }
      }
    },
    "params": {
      "title": "Parameters",
      "description": "List of parameters",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Parameter",
        "description": "Argument or attribute",
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "description": "Parameter name",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "description": "Description of the parameter",
            "type": "string"
          },
          "type": {
            "title": "Type",
            "description": "The data type of the parameter",
            "type": "string",
            "enum": [
              "any",
              "array",
              "binary",
              "boolean",
              "component",
              "date",
              "function",
              "guid",
              "numeric",
              "query",
              "string",
              "struct",
              "uuid",
              "variableName",
              "xml"
            ]
          },
          "required": {
            "title": "Required",
            "description": "Whether this parameter is required",
            "type": "boolean"
          },
          "default": {
            "title": "Default",
            "description": "The default value of the parameter when not provided",
            "type": "string",
            "default": ""
          },
          "values": {
            "title": "Values",
            "description": "List of enumerated values for the parameter",
            "type": "array",
            "minItems": 0,
            "items": {
              "title": "Value",
              "description": "One of the enumerated values for the parameter",
              "type": "string"
            },
            "default": []
          },
          "engines": {
            "title": "Engines",
            "description": "Engine compatibility information",
            "type": "object",
            "$ref": "#/definitions/engines"
          },
          "callback_params": {
            "title": "Callback Parameters",
            "description": "When type is function, this represents the parameters for the callback",
            "type": "array",
            "$ref": "#/definitions/params",
            "minItems": 0,
            "default": []
          }
        },
        "required": [
          "name",
          "description",
          "type",
          "required"
        ]
      },
      "default": []
    }
  },
  "title": "CFDocs",
  "description": "CFDocs data file",
  "type": "object",
  "properties": {
    "name": {
      "title": "Name",
      "description": "The name of the tag or function. Start with lowercase.",
      "type": "string",
      "pattern": "^[a-z]\\w+$"
    },
    "description": {
      "title": "Description",
      "description": "A short description of the item",
      "type": "string"
    },
    "type": {
      "title": "Type",
      "description": "Whether this refers to a function, tag, or listing",
      "type": "string",
      "enum": [
        "function",
        "tag",
        "listing"
      ]
    },
    "syntax": {
      "title": "Syntax",
      "description": "The basic syntax of the tag or function",
      "type": "string",
      "default": ""
    },
    "script": {
      "title": "Syntax",
      "description": "For tags, shows how the tag would be invoked from cfscript.",
      "type": "string",
      "default": ""
    },
    "member": {
      "title": "Member",
      "description": "Deprecated. For functions, shows the available member function syntax.",
      "type": "string",
      "default": ""
    },
    "member_details": {
      "title": "Member Details",
      "description": "For details of the member function equivalent of this function.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "The name of the member function. Start with lowercase.",
          "type": "string",
          "pattern": "^[a-z]\\w+$"
        },
        "type": {
          "title": "Type",
          "description": "The data type for which this function is a member",
          "type": "string",
          "enum": [
            "array",
            "boolean",
            "date",
            "image",
            "locale",
            "query",
            "string",
            "struct",
            "spreadsheet",
            "xml"
          ]
        },
        "returns": {
          "title": "Return Type",
          "description": "The return type of the member function.",
          "type": "string",
          "enum": [
            "any",
            "array",
            "binary",
            "boolean",
            "date",
            "function",
            "guid",
            "numeric",
            "query",
            "string",
            "struct",
            "uuid",
            "variableName",
            "void",
            "xml"
          ],
          "default": "void"
        },
        "engines": {
          "title": "Engines",
          "description": "Engine compatibility information",
          "type": "object",
          "$ref": "#/definitions/engines"
        },
        "base_param_index": {
          "title": "Base Param Index",
          "description": "A 1-based index referencing the param on which the member function is based",
          "type": "number",
          "default": 1
        }
      },
      "required": [
        "name",
        "type",
        "returns"
      ]
    },
    "returns": {
      "title": "Return Type",
      "description": "The return type of a function",
      "type": "string",
      "enum": [
        "any",
        "array",
        "binary",
        "boolean",
        "date",
        "function",
        "guid",
        "numeric",
        "query",
        "string",
        "struct",
        "uuid",
        "variableName",
        "void",
        "xml"
      ],
      "default": "void"
    },
    "related": {
      "title": "Related",
      "description": "A list of tag or function names that are related to this item",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Entity name",
        "description": "The name of a function or tag that is already documented",
        "type": "string"
      },
      "default": []
    },
    "discouraged": {
      "title": "Discouraged",
      "description": "If this key exists and has content a warning is displayed stating that the tag or function is discouraged by the CFML community.",
      "type": "string",
      "default": ""
    },
    "params": {
      "title": "Parameters",
      "description": "List of parameters",
      "type": "array",
      "$ref": "#/definitions/params",
      "minItems": 0,
      "default": []
    },
    "engines": {
      "title": "Engines",
      "description": "Engine compatibility information",
      "type": "object",
      "$ref": "#/definitions/engines"
    },
    "links": {
      "title": "Links",
      "description": "A list of external references",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Link",
        "description": "Information about the reference",
        "type": "object",
        "properties": {
          "title": {
            "title": "Title",
            "description": "A title for the link",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "description": "A description for the link",
            "type": "string"
          },
          "url": {
            "title": "URL",
            "description": "The link URL",
            "type": "string"
          }
        },
        "required": [
          "title",
          "description",
          "url"
        ]
      },
      "default": []
    },
    "examples": {
      "title": "Examples",
      "description": "A list of examples",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Example",
        "description": "Information about the example",
        "type": "object",
        "properties": {
          "title": {
            "title": "Title",
            "description": "Name of the code example",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "description": "Description of the code example",
            "type": "string"
          },
          "code": {
            "title": "Code",
            "description": "The example code",
            "type": "string"
          },
          "result": {
            "title": "Result",
            "description": "The expected output of the code example",
            "type": "string"
          },
          "runnable": {
            "title": "Runnable",
            "description": "Whether the code is runnable",
            "type": "boolean"
          }
        },
        "required": [
          "title",
          "description",
          "code"
        ]
      },
      "default": []
    }
  },
  "required": [
    "name",
    "description",
    "type"
  ]
}

=== foundeo/cfdocs/data/en/tan.json
{
	"name":"tan",
	"type":"function",
	"syntax":"tan(number)",
	"returns":"numeric",
	"related":["acos","asin","atn","cos","exp","log","log10","sin"],
	"description":" Calculates the tangent of an angle that is entered in radians.",
	"params": [
		{"name":"number","description":"Angle, in radians, for which to calculate the tangent","required":true,"default":"","type":"numeric","values":[]}

	],
	"engines": {
		"coldfusion": {"minimum_version":"", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-t-z/tan.html"},
		"lucee": {"minimum_version":"", "notes":"", "docs":"https://docs.lucee.org/reference/functions/tan.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/function/tan"},
		"openbd": {"minimum_version":"", "notes":"", "docs":"http://openbd.org/manual/?/function/tan"}
	},
	"links": [

	],
	"examples": [
		{
			"title":"Tangent of 0.3",
			"description":"",
			"code":"tan(0.3)",
			"result":"0.30933624961",
			"runnable":true
		}
	]

}

=== foundeo/cfdocs/data/en/structsetmetadata.json
{
	"name":"structSetMetadata",
	"type":"function",
	"syntax":"structSetMetadata(inputStruct, metaStruct)",
	"returns":"void",
	"related":["arraySetMetadata","arrayGetMetadata","structGetMetadata"],
	"member":"inputStruct.setMetadata(metaStruct)",
	"description":"Sets metadata for a key in a struct. When you want to SerializeJSON, the key and the value will be display as you defined in the metadata.",
	"params": [
		{"name":"inputStruct","description":"The struct in which you want to add the metadata.","required":true,"default":"","type":"struct","values":[]},
		{"name":"metaStruct","description":"The metadata struct you want to add.","required":true,"default":"","type":"struct","values":[]}
	],
	"engines": {
		"coldfusion": {"minimum_version":"2016.0.2", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-s/structsetmetadata.html"}
	},
    	"links": [],
    	"examples": [
		{
			"title":"Add metadata to a struct",
			"description":"Add metadata to a struct and serialze to a json.\nIt is changing the keyname and convert a string (\"20\") to a number.",
			"code":"testStruct = structNew(\"ordered\");\ntestStruct.testdata = \"example\";\ntestStruct.testdata2 = \"20\";\nmetadata = {\n    testdata: {type: \"string\", name: \"td1\" },\n    testdata2: {type: \"numeric\", name: \"td2\" }\n};\nStructSetMetaData(testStruct,metadata);\nwriteoutput(SerializeJSON(testStruct));",
			"result":"{\"td1\":\"example\", \"td2\":20.0}",
			"runnable": true
		},
		{
			"title":"Add metadata to a struct as a member function",
			"description":"Add metadata to a struct and serialze to a json.\nIt is changing the keyname and convert a string (\"20\") to a number.",
			"code":"testStruct = structNew(\"ordered\");\ntestStruct.testdata = \"example\";\ntestStruct.testdata2 = \"20\";\nmetadata = {\n    testdata: {type: \"string\", name: \"td1\" },\n    testdata2: {type: \"numeric\", name: \"td2\" }\n};\ntestStruct.setMetadata(metadata);\nwriteoutput(SerializeJSON(testStruct));",
			"result":"{\"td1\":\"example\", \"td2\":20.0}",
			"runnable": true
		}
	]
}

=== foundeo/cfdocs/data/en/isvalid.json
{
	"name":"isValid",
	"type":"function",
	"syntax":"isValid(type, value, min, max, pattern)",
	"returns":"boolean",
	"related":["isarray", "issimplevalue","isnumeric","isboolean","isdate","cfparam"],
	"description":"Tests whether a value meets a validation or data type rule.",
	"params": [
		{"name":"type","description":"The valid format for the data.","required":true,"default":"","type":"string","values":["any", "array", "binary", "boolean", "component", "creditcard", "date", "email", "eurodate", "float", "function", "guid", "integer", "numeric", "query", "range", "regex", "regular_expression", "social_security_number", "ssn", "string", "struct", "telephone", "time", "url", "usdate", "uuid", "variablename", "xml", "zipcode"]},
		{"name":"value","description":"The value to test.","required":true,"default":"","type":"any","values":[]},
		{"name":"min","description":"The minimum valid value; used only for range validation.","required":false,"default":"","type":"numeric","values":[]},
		{"name":"max","description":"The maximum valid value; used only for range validation.","required":false,"default":"","type":"numeric","values":[]},
		{"name":"pattern","description":"A regular expression that the parameter must match;\n used only for regex or regular_expression validation.","required":false,"default":"","type":"string","values":[]}
	],
	"engines": {
		"coldfusion": {"minimum_version":"7", "notes":"CF8+ - added component as a type option.\nCF11+ - no longer allows currency symbols at the start and commas inside a number. Can be reverted to legacy mode by setting this.strictNumberValidation = false in Application.cfc", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-in-k/isvalid.html"},
		"lucee": {"minimum_version":"", "notes":"", "docs":"https://docs.lucee.org/reference/functions/isvalid.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/function/isvalid"},
		"openbd": {"minimum_version":"", "notes":"", "docs":"http://openbd.org/manual/?/function/isvalid"},
		"boxlang": {"minimum_version":"1.0.0", "notes":"", "docs":"https://boxlang.ortusbooks.com/boxlang-language/reference/built-in-functions/decision/isvalid"}
	},
	"links": [

	],
	"examples": [
		{
			"title":"Check to see if a 235 is an integer",
			"description":"Use the isValid function with integer as the type.",
			"code":"isValid(\"integer\", 235)",
			"result":"true"
		},
		{
			"title":"Validate an Email Address",
			"description":"Use the isValid function with email as the type.",
			"code":"isValid(\"email\", \"user@example.com\")",
			"result":"true"
		}
	]

}

=== foundeo/cfdocs/data/en/imagecrop.json
{
	"name":"imageCrop",
	"type":"function",
	"syntax":"imageCrop(name, x, y, width, height)",
	"member":"someImage.crop(x, y, width, height)",
	"returns":"void",
	"related":["imageResize"],
	"description":"Crops a ColdFusion image to a specified rectangular area.",
	"params": [
		{"name":"name","description":"The image on which this operation is performed.","required":true,"default":"","type":"string","values":[]},
		{"name":"x","description":"The X origin of the crop area.","required":true,"default":"","type":"numeric","values":[]},
		{"name":"y","description":"The Y origin of the crop area.","required":true,"default":"","type":"numeric","values":[]},
		{"name":"width","description":"The width of the crop area.","required":true,"default":"","type":"numeric","values":[]},
		{"name":"height","description":"The height of the crop area.","required":true,"default":"","type":"numeric","values":[]}
	],
	"engines": {
		"coldfusion": {"minimum_version":"8", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-h-im/imagecrop.html"},
		"lucee": {"minimum_version":"4.5", "notes":"", "docs":"https://docs.lucee.org/reference/functions/imagecrop.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/function/imagecrop"},
		"openbd": {"minimum_version":"", "notes":"", "docs":"http://openbd.org/manual/?/function/imagecrop"}
	},
	"links": [],
    	"examples": [
		{
			"title": "Tag Syntax",
			"description": "This example shows how to crop an image.",
			"code": "<!--- Create a ColdFusion image from an existing JPEG file. ---> \r\n <cfimage source=\"../cfdocs/images/artgallery/lori05.jpg\" name=\"myImage\"> \r\n <!--- Crop myImage to 100x100 pixels starting at the coordinates (10,10). ---> \r\n <cfset imageCrop(myImage,10,10,100,100)> \r\n <!--- Write the result to a file. ---> \r\n <cfimage source=\"#myImage#\" action=\"write\" destination=\"test_myImage.jpg\" overwrite=\"yes\"> \r\n <!--- Display the source image and the new image. ---> \r\n <img src=\"../cfdocs/images/artgallery/lori05.jpg\"/> \r\n <img src=\"test_myImage.jpg\"/>  ",
			"result": "",
			"runnable": false
		},
		{
			"title":"Using crop member function",
			"description":"CF11+ Lucee4.5+ Crop the image from starting point (x=25, y=25), with width=100 and height=100",
			"code":"imgObj = imageRead(\"http://cfdocs.org/apple-touch-icon.png\");\r\nimgObj.crop(25,25,100,100);\r\ncfimage(action=\"writeToBrowser\", source=imgObj);",
			"result":"",
			"runnable":true
		}
	]
}

=== foundeo/cfdocs/data/en/cachegetdefaultcachename.json
{
	"name": "cacheGetDefaultCacheName",
	"type": "function",
	"syntax": "cacheGetDefaultCacheName(type)",
	"returns": "string",
	"related": [],
	"description": "Returns the default cache name for the specified type.",
	"params": [
		{"name": "type", "description": "Cache type", "required": true, "default": "", "type": "string", "values": ["object","resource","template","query"]}
	],
	"engines": {
		"lucee": {"minimum_version": "", "notes": "", "docs": "https://docs.lucee.org/reference/functions/cachegetdefaultcachename.html"}
	},
	"examples": [],
	"links": []
}

=== foundeo/cfdocs/data/en/filereadbinary.json
{
	"name":"fileReadBinary",
	"type":"function",
	"syntax":"fileReadBinary(filePath)",
	"returns":"binary",
	"related":["fileRead","fileReadLine"],
	"description":"Reads an on-disk or in-memory binary file (such as an executable or image file) on the server, into a binary object",
	"params": [
		{"name":"filePath","description":"Absolute path to the file.","required":true,"default":"","type":"string","values":[]}
	],
	"engines": {
		"coldfusion": {"minimum_version":"8", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-e-g/filereadbinary.html"},
		"lucee": {"minimum_version":"", "notes":"", "docs":"https://docs.lucee.org/reference/functions/filereadbinary.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/function/filereadbinary"},
		"openbd": {"minimum_version":"", "notes":"", "docs":"http://openbd.org/manual/?/function/filereadbinary"}
	},
	"links": [],
	"examples": [
		{
			"title": "Read a file into a binary object",
			"description": "Uses expandPath to grab a file in current directory.",
			"code": "binaryContent = fileReadBinary(expandPath('./file.pdf');",
			"result": "",
			"runnable": false
		}
	]
}

=== foundeo/cfdocs/data/en/getwriteableimageformats.json
{
	"name":"getWriteableImageFormats",
	"type":"function",
	"syntax":"getWriteableImageFormats()",
	"returns":"string",
	"related":[],
	"description":" No Help Available",
	"params": [
	],
	"engines": {
		"coldfusion": {"minimum_version":"", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-e-g/getwriteableimageformats.html"},
		"lucee": {"minimum_version":"", "notes":"", "docs":"https://docs.lucee.org/reference/functions/getwriteableimageformats.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/function/getwriteableimageformats"}
	},
	"links": [

	]

}

=== foundeo/cfdocs/data/en/imagefiltercurves.json
{
	"name": "imageFilterCurves",
	"type": "function",
	"syntax": "imageFilterCurves()",
	"returns": "any",
	"related": ["imageFilterColorMap","imageFilter","imageFilterKernel","imageFilterWarpGrid"],
	"description": "",
	"params": [],
	"engines": {
		"lucee": {"minimum_version": "", "notes": "", "docs": "https://docs.lucee.org/reference/functions/imagefiltercurves.html"}
	},
	"examples": [],
	"links": []
}
