=== foundeo/cfdocs/data/cfdocs.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "engineDetail": {
      "title": "Engine Detail",
      "type": "object",
      "properties": {
        "minimum_version": {
          "title": "Minimum version",
          "description": "The version of the engine in which this was introduced",
          "type": "string",
          "pattern": "^((0|[1-9]\\d*)(\\.(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))?)?)?$"
        },
        "deprecated": {
          "title": "Deprecated version",
          "description": "The version of the engine in which this was deprecated",
          "type": "string",
          "pattern": "^((0|[1-9]\\d*)(\\.(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))?)?)?$",
          "default": ""
        },
        "removed": {
          "title": "Removed version",
          "description": "The version of the engine in which this was removed",
          "type": "string",
          "pattern": "^((0|[1-9]\\d*)(\\.(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))?)?)?$",
          "default": ""
        },
        "notes": {
          "title": "Notes",
          "description": "Additional notes about engine compatibility",
          "type": "string",
          "default": ""
        },
        "docs": {
          "title": "Docs",
          "description": "Link to engine-specific documentation",
          "type": "string",
          "default": ""
        }
      },
      "required": [
        "minimum_version"
      ]
    },
    "engines": {
      "title": "Engines",
      "type": "object",
      "properties": {
        "coldfusion": {
          "title": "ColdFusion",
          "description": "Engine details for ColdFusion",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        },
        "railo": {
          "title": "Railo",
          "description": "Engine details for Railo",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        },
        "lucee": {
          "title": "Lucee",
          "description": "Engine details for Lucee",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        },
        "openbd": {
          "title": "OpenBD",
          "description": "Engine details for OpenBD",
          "type": "object",
          "$ref": "#/definitions/engineDetail"
        }
      }
    },
    "params": {
      "title": "Parameters",
      "description": "List of parameters",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Parameter",
        "description": "Argument or attribute",
        "type": "object",
        "properties": {
          "name": {
            "title": "Name",
            "description": "Parameter name",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "description": "Description of the parameter",
            "type": "string"
          },
          "type": {
            "title": "Type",
            "description": "The data type of the parameter",
            "type": "string",
            "enum": [
              "any",
              "array",
              "binary",
              "boolean",
              "component",
              "date",
              "function",
              "guid",
              "numeric",
              "query",
              "string",
              "struct",
              "uuid",
              "variableName",
              "xml"
            ]
          },
          "required": {
            "title": "Required",
            "description": "Whether this parameter is required",
            "type": "boolean"
          },
          "default": {
            "title": "Default",
            "description": "The default value of the parameter when not provided",
            "type": "string",
            "default": ""
          },
          "values": {
            "title": "Values",
            "description": "List of enumerated values for the parameter",
            "type": "array",
            "minItems": 0,
            "items": {
              "title": "Value",
              "description": "One of the enumerated values for the parameter",
              "type": "string"
            },
            "default": []
          },
          "engines": {
            "title": "Engines",
            "description": "Engine compatibility information",
            "type": "object",
            "$ref": "#/definitions/engines"
          },
          "callback_params": {
            "title": "Callback Parameters",
            "description": "When type is function, this represents the parameters for the callback",
            "type": "array",
            "$ref": "#/definitions/params",
            "minItems": 0,
            "default": []
          }
        },
        "required": [
          "name",
          "description",
          "type",
          "required"
        ]
      },
      "default": []
    }
  },
  "title": "CFDocs",
  "description": "CFDocs data file",
  "type": "object",
  "properties": {
    "name": {
      "title": "Name",
      "description": "The name of the tag or function. Start with lowercase.",
      "type": "string",
      "pattern": "^[a-z]\\w+$"
    },
    "description": {
      "title": "Description",
      "description": "A short description of the item",
      "type": "string"
    },
    "type": {
      "title": "Type",
      "description": "Whether this refers to a function, tag, or listing",
      "type": "string",
      "enum": [
        "function",
        "tag",
        "listing"
      ]
    },
    "syntax": {
      "title": "Syntax",
      "description": "The basic syntax of the tag or function",
      "type": "string",
      "default": ""
    },
    "script": {
      "title": "Syntax",
      "description": "For tags, shows how the tag would be invoked from cfscript.",
      "type": "string",
      "default": ""
    },
    "member": {
      "title": "Member",
      "description": "Deprecated. For functions, shows the available member function syntax.",
      "type": "string",
      "default": ""
    },
    "member_details": {
      "title": "Member Details",
      "description": "For details of the member function equivalent of this function.",
      "type": "object",
      "properties": {
        "name": {
          "title": "Name",
          "description": "The name of the member function. Start with lowercase.",
          "type": "string",
          "pattern": "^[a-z]\\w+$"
        },
        "type": {
          "title": "Type",
          "description": "The data type for which this function is a member",
          "type": "string",
          "enum": [
            "array",
            "boolean",
            "date",
            "image",
            "locale",
            "query",
            "string",
            "struct",
            "spreadsheet",
            "xml"
          ]
        },
        "returns": {
          "title": "Return Type",
          "description": "The return type of the member function.",
          "type": "string",
          "enum": [
            "any",
            "array",
            "binary",
            "boolean",
            "date",
            "function",
            "guid",
            "numeric",
            "query",
            "string",
            "struct",
            "uuid",
            "variableName",
            "void",
            "xml"
          ],
          "default": "void"
        },
        "engines": {
          "title": "Engines",
          "description": "Engine compatibility information",
          "type": "object",
          "$ref": "#/definitions/engines"
        },
        "base_param_index": {
          "title": "Base Param Index",
          "description": "A 1-based index referencing the param on which the member function is based",
          "type": "number",
          "default": 1
        }
      },
      "required": [
        "name",
        "type",
        "returns"
      ]
    },
    "returns": {
      "title": "Return Type",
      "description": "The return type of a function",
      "type": "string",
      "enum": [
        "any",
        "array",
        "binary",
        "boolean",
        "date",
        "function",
        "guid",
        "numeric",
        "query",
        "string",
        "struct",
        "uuid",
        "variableName",
        "void",
        "xml"
      ],
      "default": "void"
    },
    "related": {
      "title": "Related",
      "description": "A list of tag or function names that are related to this item",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Entity name",
        "description": "The name of a function or tag that is already documented",
        "type": "string"
      },
      "default": []
    },
    "discouraged": {
      "title": "Discouraged",
      "description": "If this key exists and has content a warning is displayed stating that the tag or function is discouraged by the CFML community.",
      "type": "string",
      "default": ""
    },
    "params": {
      "title": "Parameters",
      "description": "List of parameters",
      "type": "array",
      "$ref": "#/definitions/params",
      "minItems": 0,
      "default": []
    },
    "engines": {
      "title": "Engines",
      "description": "Engine compatibility information",
      "type": "object",
      "$ref": "#/definitions/engines"
    },
    "links": {
      "title": "Links",
      "description": "A list of external references",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Link",
        "description": "Information about the reference",
        "type": "object",
        "properties": {
          "title": {
            "title": "Title",
            "description": "A title for the link",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "description": "A description for the link",
            "type": "string"
          },
          "url": {
            "title": "URL",
            "description": "The link URL",
            "type": "string"
          }
        },
        "required": [
          "title",
          "description",
          "url"
        ]
      },
      "default": []
    },
    "examples": {
      "title": "Examples",
      "description": "A list of examples",
      "type": "array",
      "minItems": 0,
      "items": {
        "title": "Example",
        "description": "Information about the example",
        "type": "object",
        "properties": {
          "title": {
            "title": "Title",
            "description": "Name of the code example",
            "type": "string"
          },
          "description": {
            "title": "Description",
            "description": "Description of the code example",
            "type": "string"
          },
          "code": {
            "title": "Code",
            "description": "The example code",
            "type": "string"
          },
          "result": {
            "title": "Result",
            "description": "The expected output of the code example",
            "type": "string"
          },
          "runnable": {
            "title": "Runnable",
            "description": "Whether the code is runnable",
            "type": "boolean"
          }
        },
        "required": [
          "title",
          "description",
          "code"
        ]
      },
      "default": []
    }
  },
  "required": [
    "name",
    "description",
    "type"
  ]
}

=== foundeo/cfdocs/data/en/arrayresize.json
{
	"name":"arrayResize",
	"type":"function",
	"syntax":"arrayResize(array, size)",
	"member":"someArray.resize(size)",
	"returns":"boolean",
	"related":[],
	"description":"Resets an array to a specified minimum number of elements.\n This can improve performance, if used to size an array to its\n expected maximum. For more than 500 elements, use arrayResize\n immediately after using the ArrayNew tag.",
	"params": [
		{"name":"array","description":"","required":true,"default":"","type":"array","values":[]},
		{"name":"size","description":"","required":true,"default":"","type":"numeric","values":[]}

	],
	"engines": {
		"coldfusion": {"minimum_version":"3", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-a-b/arrayresize.html"},
		"lucee": {"minimum_version":"", "notes":"", "docs":"https://docs.lucee.org/reference/functions/arrayresize.html"},
		"openbd": {"minimum_version":"", "notes":"", "docs":"http://openbd.org/manual/?/function/arrayresize"}
	},
	"links": [

	],
	"examples": [
		{
			"title": "Tag Syntax",
			"description": "",
			"code": "<cfset MyArray = arrayNew(1)> \r\n <!--- Resize that array to the number of records in the query. ---> \r\n <cfset temp = arrayResize(MyArray, 8)> \r\n  <cfdump var=\"#MyArray#\" />  ",
			"result": ""
		}
	]

}

=== foundeo/cfdocs/data/en/querydeleterow.json
{
	"name": "queryDeleteRow",
	"type": "function",
	"syntax": "queryDeleteRow(query [, row])",
	"member": "query.deleteRow([row])",
	"returns": "boolean",
	"related": [],
	"description": "Deletes a row within a query object.",
	"params": [
		{"name": "query", "description": "Query to modify", "required": true, "default": "", "type": "query", "values": []},
		{"name": "row", "description": "Index of the row to delete, starts at 1.  If a row is not specified, the last row is removed.", "required": false, "default": "-9999", "type": "numeric", "values": []}
	],
	"engines": {
		"lucee": {"minimum_version": "", "notes": "", "docs": "https://docs.lucee.org/reference/functions/querydeleterow.html"},
		"coldfusion": {"minimum_version": "2018", "notes": "", "docs": "https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-m-r/querydeleterow.html"}
	},
	"examples": [
		{
			"title":"Implicit deletion of the last row",
			"description":"Builds a simple query and removes the last row by not specifying a row index.",
			"code":"news = queryNew(\"id,title\", \"integer,varchar\", [ {\"id\":1,\"title\":\"Dewey defeats Truman\"}, {\"id\":2,\"title\":\"Man walks on Moon\"} ]);\nqueryDeleteRow(news);\nwriteOutput(news['title'][1]);",
			"result":"Dewey defeats Truman"
		},
		{
			"title":"Deletes a specific row from the query",
			"description":"Builds a simple query and removes one of the rows.",
			"code":"news = queryNew(\"id,title\", \"integer,varchar\", [ {\"id\":1,\"title\":\"Dewey defeats Truman\"}, {\"id\":2,\"title\":\"Man walks on Moon\"} ]);\nqueryDeleteRow(news, 1);\nwriteOutput(news['title'][1]);",
			"result":"Man walks on Moon"
		}
	],
	"links": []
}

=== foundeo/cfdocs/data/en/imageoverlay.json
{
	"name":"imageOverlay",
	"type":"function",
	"syntax":"imageOverlay(source1, source2 [, rule, alpha])",
	"member":"someImage.overlay(source2 [, rule, alpha])",
	"returns":"void",
	"related":[],
	"description":" Reads two source ColdFusion images and overlays the second source image on the first source image.",
	"params": [
		{"name":"source1","description":"The image that is the bottom layer in the image.","required":true,"default":"","type":"string","values":[]},
		{"name":"source2","description":"The image that is the top layer (overlaid on the source1 image) in the image.","required":true,"default":"","type":"string","values":[]},
		{"name":"rule","description":"CF10+ Compositing Rule","required":false,"default":"","type":"string","values":["SRC","DST_IN","DST_OUT","DST_OVER","SRC_IN","SRC_OVER","SRC_OUT"]},
		{"name":"alpha","description":"CF10+ The percentage value of transparency","required":false,"default":"","type":"string","values":[]}

	],
	"engines": {
		"coldfusion": {"minimum_version":"8", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-h-im/imageoverlay.html"},
		"lucee": {"minimum_version":"4.5", "notes":"", "docs":"https://docs.lucee.org/reference/functions/imageoverlay.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/function/imageoverlay"}
	},
	"links": [

	],
    "examples": [
		{
			"title": "Tag Syntax",
			"description": "This example shows how to overlay a smaller image on a larger image. ",
			"code": "<!--- Create a ColdFusion image from an existing JPEG file and enlarge it by 150%. This image is displayed in the background. --->\r\n<cfimage source=\"../cfdocs/images/artgallery/maxwell01.jpg\" name=\"myImage\" action=\"resize\" width=\"150%\" height=\"150%\">\r\n <!--- Turn on antialiasing to improve image quality. --->\r\n<cfset imageSetAntialiasing(myImage,\"on\")>\r\n<!--- Create a ColdFusion image from an existing JPEG file. This image is overlaid on the background image. --->\r\n<cfimage source=\"../cfdocs/images/artgallery/viata05.jpg\" name=\"topImage\">\r\n<!--- Overlay the top image on the background image. --->\r\n<cfset imageOverlay(myImage,topImage)>\r\n<!--- Display the combined image in a browser. --->\r\n<cfimage source=\"#myImage#\" action=\"writeToBrowser\"> ",
			"result": "",
			"runnable":false
		},
		{
			"title":"Using overlay member function",
			"description":"CF11+ Lucee4.5+ Overlay one image on the other",
			"code":"imgObj = imageNew(\"\",152,152,\"rgb\",\"149c82\");\r\ntopImg = imageNew(\"\",50,50,\"rgb\",\"ffffff\");\r\nimgObj.overlay(topImg);\r\ncfimage(action=\"writeToBrowser\", source=imgObj);",
			"result":"",
			"runnable":true
		}
	]

}

=== foundeo/cfdocs/data/en/ormreload.json
{
	"name":"ormReload",
	"type":"function",
	"syntax":"ormReload()",
	"returns":"void",
	"related":[],
	"description":"Reinitializes ORM for the application.If you make any change to the persistent metadata of the CFCs, then you might want to reload the ORM.  Returns ORM session factory instance",
	"params": [
	],
	"engines": {
		"coldfusion": {"minimum_version":"", "notes":"", "docs":"https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-m-r/ormreload.html"},
		"lucee": {"minimum_version":"", "notes":"", "docs":"https://docs.lucee.org/reference/functions/ormreload.html"},
		"railo": {"minimum_version":"", "notes":"", "docs":"http://railodocs.org/index.cfm/function/ormreload"}
	},
	"links": [

	],
	"examples": [
		{
			"title": "Reload ORM by calling ormReload onRequestStart",
			"description": "Reloads the ORM of an application when ?ORMReload is in the URL.  This is recommeded ONLY for development and should be removed from production.",
			"code": "component { \r\n\tthis.name = hash(getCurrentTemplatePath()); \r\n\tthis.datasource = \"somedatasourceORM\"; \r\n\t// turn on ORM for this application\r\n\tthis.ormenabled = true; \r\n\tpublic boolean function onRequestStart(required string targetPage) {\r\n\t\t//if ormreload is in the URL, then reload ORM\r\n\t\tif (structKeyExists(url,\"ormreload\")){\r\n\t\t\tORMReload()\r\n\t\t}\r\n\t\treturn true;\r\n\t}\r\n}",
			"result": "string"
		}
	]
}

=== foundeo/cfdocs/data/en/cfsprydataset.json
{
	"name": "cfsprydataset",
	"type": "tag",
	"syntax": "<cfsprydataset bind=\"\" name=\"\">",
	"related": [],
	"description": "Creates a Spry data set; can use bind parameters to get data from ColdFusion AJAX controls \n to populate the data set.",
	"params": [
		{
			"name": "bind",
			"description": "A bind expression that returns XML data to populate \n the Spry data set. The bind expression can specify a \n CFC function or URL and can include bind parameters \n that represent the values of ColdFusion controls. For \n detailed information on specifying bind expressions, \n see HTML form data binding in cfinput.",
			"required": true,
			"default": "",
			"type": "string",
			"values": []
		},
		{
			"name": "name",
			"description": "The name of the Spry data set.",
			"required": true,
			"default": "",
			"type": "string",
			"values": []
		},
		{
			"name": "onbinderror",
			"description": "The name of a JavaScript function to execute if \n evaluating the bind expression results in an error. The \n function must take two attributes: an HTTP status \n code and a message. \n If you omit this attribute, and have specified a global \n error handler (by using the \n ColdFusion.setGlobalErrorHandler function), the \n handler displays the error message; otherwise a \n default error pop-up displays.",
			"required": false,
			"default": "",
			"type": "string",
			"values": []
		},
		{
			"name": "options",
			"description": "A JavaScript object containing options to pass to the \n data set.",
			"required": false,
			"default": "",
			"type": "string",
			"values": []
		},
		{
			"name": "type",
			"description": "Specifies data set type, corresponding to the format of \n the data that is returned by the bind expression.",
			"required": false,
			"default": "",
			"type": "string",
			"values": ["xml", "json"]
		},
		{
			"name": "xpath",
			"description": "Valid for XML type data sets only. An XPath \n expression that extracts data from the XML returned \n by the bind expression. The data set contains only the \n data that matches the xpath expression.",
			"required": false,
			"default": "",
			"type": "string",
			"values": []
		}
	],
	"engines": {
		"coldfusion": {
			"minimum_version": "8",
			"notes": "",
			"docs": "https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-r-s/cfsprydataset.html",
			"deprecated":"11"
		}
	},
	"links": []
}

=== foundeo/cfdocs/data/en/querylazy.json
{
	"name": "querylazy",
	"type": "function",
	"syntax": "querylazy()",
	"returns": "void",
	"description": "Executes a SQL query without loading the data entirely to memory. Instead it calls the given Function with every single row",
	"params": [
		{
			"default": "",
			"required": true,
			"values": [],
			"name": "sql",
			"type": "string",
			"description": "SQL to execute"
		},
		{
			"default": "",
			"required": true,
			"values": [],
			"name": "listener",
			"type": "function",
			"description": "listener function that will be called with the data of every single row. if returns false, execution is stopped."
		},
		{
			"default": "",
			"required": false,
			"values": [],
			"name": "params",
			"type": "any",
			"description": "Array or Struct of parameter values. \n    \t\t\tWhen passing an array use ? as place holders. \n    \t\t\tWhen passing a struct use :keyName where keyName is the name of the key in the structure corresponding to\n    \t\t\tthe parameter. \n    \t\t\tThe struct or array can be a struct with keys such as the following: cfsqltype, list"
		},
		{
			"default": "",
			"required": false,
			"values": [],
			"name": "options",
			"type": "struct",
			"description": "Struct containing query options, all cfquery tag attributes are supported except the name attribute."
		}
	],
	"engines": {
		"lucee": {
			"notes": "",
			"minimum_version": "5.3.6",
			"docs": "https://docs.lucee.org/reference/functions/querylazy.html"
		}
	},
	"examples": [
		{
			"title": "QueryLazy Example",
			"description": "This example demonstrates how to use the querylazy function to execute a query without loading the data entirely to memory.",
			"code": "records = 0\n queryLazy(\n sql=\"SELECT * FROM users;\",\n listener=function(row){\n // Do something with a query row\n records++;\n },\n options={\n datasource:\"MyDatasource\"\n }\n );\n echo(\"Records: #records#\");",
			"result": "Records: 10"
		}
	]
}

=== foundeo/cfdocs/data/en/structevery.json
{
	"name": "structEvery",
	"type": "function",
	"syntax": "structEvery(struct, closure [, parallel] [, maxThreads])",
	"member": "struct.every(closure [, parallel] [, maxThreads])",
	"returns": "boolean",
	"related": [],
	"description": "This function calls a given closure/function with every element in a given struct and returns true, if all of the closure calls returns true",
	"params": [
		{"name": "struct", "description": "", "required": true, "default": "", "type": "struct", "values": []},
		{"name": "closure", "description": "", "required": true, "default": "", "type": "function", "values": []},
		{"name": "parallel", "description": "", "required": false, "default": "", "type": "boolean", "values": []},
		{"name": "maxThreads", "description": "", "required": false, "default": "20", "type": "numeric", "values": []}
	],
	"engines": {
		"lucee": {"minimum_version": "", "notes": "", "docs": "https://docs.lucee.org/reference/functions/structevery.html"}
	},
	"examples": [
		{
			"title":"Simple structEvery example",
			"description":"Here we have simple example about structevery function. It is supported only in Lucee.",
			"code":"var struct = {\"Name\":\"Dhar\",\"Age\":\"20\",\"Country\":\"US\"};\r\nstructevery(struct,function(key,value){\r\n\twriteOutput(key & \":\" & value & \" \");\r\n\treturn true;\r\n});",
			"result":"Country:US Name:Dhar Age:20"
		},
		{
			"title":"Simple structEvery member function example",
			"description":"Here we have simple example about structevery member function. It is supported only in Lucee.",
			"code":"var struct = {\"Name\":\"Dhar\",\"Age\":\"20\",\"Country\":\"US\"};\r\nstruct.every(function(key,value){\r\n\twriteOutput(key & \":\" & value & \" \");\r\n\treturn false;\r\n});",
			"result":"Country:US"
		}
	],
	"links": [{
		"title":"Map, Reduce and other Higher Order Functions",
		"description":"A Primer for map, reduce, filter, and Higher Order Functions in general.",
		"url":"http://ryanguill.com/functional/higher-order-functions/2016/05/18/higher-order-functions.html"
	}]
}

=== foundeo/cfdocs/data/en/componentcacheclear.json
{
	"name": "componentCacheClear",
	"type": "function",
	"syntax": "componentCacheClear()",
	"returns": "void",
	"related": ["componentCacheList","getComponentMetadata","cfcomponent","cfcache"],
	"description": "This function flushes the component path cache",
	"params": [],
	"engines": {
		"lucee": {"minimum_version": "", "notes": "", "docs": "http://docs.lucee.org/reference/functions/componentcacheclear.html"}
	},
	"examples": [],
	"links": []
}
